### PR TITLE
Update fuzzy_overlay.py

### PR DESCRIPTION
**Pull request by RichardScottOZ**
minor edits

### CODE REVIEW

**Comment by nmaarnio** [comment]
Hey, thanks for spotting these :+1: I'll go ahead and merge

**Review by nmaarnio — APPROVED** [review]

**Review by RichardScottOZ — COMMENTED** [review]
Ok, why the change from
```python
sum = sum_overlay(data=data)
product = product_overlay(data=data)
return product ** (1 - gamma) * sum**gamma
```
to

```python
product = np.prod(data, axis=0)
sum = data.sum(axis=0) - product
```
```python
return product ** (1 - gamma) * sum**gamma
```

**Comment by nmaarnio** [comment]
> Ok, why the change from
> 
> ```python
> sum = sum_overlay(data=data)
> product = product_overlay(data=data)
> return product ** (1 - gamma) * sum**gamma
> ```
> 
> to
> 
> ```python
> product = np.prod(data, axis=0)
> sum = data.sum(axis=0) - product
> ```
> 
> ```python
> return product ** (1 - gamma) * sum**gamma
> ```

I don't recall exactly, but now that I quickly checked the code, probably just so that `_prepare_data_for_fuzzy_overlay` wouldn't be run 3 times. Not a necessary change, but then again the functions are simple enough at the moment to be maintainable like this.

**Comment by RichardScottOZ** [comment]
Right, that makes sense!

**Pull request merged**
