### PR TITLE
Add optimized version of distance computation

### PR DESCRIPTION
**Pull request by msorvoja**
Adds an optimized version of distance computation using spatial indexing (`scipy.spatial.cKDTree`) for nearest neighbor search and Numba (`njit` decorator) for more efficient computation of distances. Old and new implementation are compared in `notebooks/testing_distance_computation.ipynb`.

### CODE REVIEW

**Comment by nmaarnio** [comment]
The final optimized version does not use `cKDTree`, only Numba.

Performance comparison of old and new version:

###  Geometries: Line dataset with 85 feature

**Old version**
- Raster with 2.2M pixels: 42s
- Raster with 13.9M pixels: 367s (~6min)
- Raster with 55.8M pixles: ?

**New version**
- Raster with 2.2M pixels: 4s (10x speedup)
- Raster with 13.9M pixels: 12s (30x speedup)
- Raster with 55.8M pixles: 56s


### Geometries: Polygon dataset with 8 features

**Old version**
- Raster with 2.2M pixels: 22s
- Raster with 13.9M pixels: 160s
- Raster with 55.8M pixles: ?

**New version**
- Raster with 2.2M pixels: 2s (11x speedup)
- Raster with 13.9M pixels: 3s (53x speedup)
- Raster with 55.8M pixles: 8s

**Review by nmaarnio — APPROVED** [review]
I cannot approve this alone since I was heavily involved in the creation of the last optimized version.

@msorvoja , can you check that everything works and seems ok still?
@Mtk112 , if you do a quick check that the distribution with this version works on Windows (with the changed dependencies) and report back here

**Comment by msorvoja** [comment]
@nmaarnio Tested with IOCG point, line and polygon data, and the results look good to me!

**Comment by nmaarnio** [comment]
There was a bug @Mtk112 noticed that occurred for some numpy and rasterio versions on Windows at least. It should be fixed now.

This PR should be ready to be merged now 🚀

**Pull request merged**
