### PR TITLE
added smote code and test code

### PR DESCRIPTION
**Pull request by dipak5053**
I created and added the code for SMOTE

### CODE REVIEW

**Review by msorvoja — CHANGES_REQUESTED** [review]
Hi! Thank you for you PR. I have left you some feedback on some technicalities details in the code. Please read them through and make suggested changes and let me know if you have any questions.

I'm also wondering which package (=folder) would be most appropriate for this kind of function. Couldn't find this in MS Teams files. Do you @nmaarnio have any ideas?

**Comment by nmaarnio** [comment]
Thanks for the code @dipak5053 , I examined the code you provided, adjusted the core contents to fit to EIS Toolkit and created a new pull request. Consequently, I will close this PR now.

**Comment by dipak5053** [comment]
Dear Niko,

Thank you for  your email and your support.

Did I understand correctly that this pull request is okay and I do not have
to do anything more?

Warm regards,
Dipak

**Comment by nmaarnio** [comment]
Yes, regarding this pull request and SMOTETomek, there is no need to do more!

**Pull request closed without merging**
