### PR TITLE
Support conda development environment (Closes #87)

### LINKED ISSUE #87: Support a development environment with `conda`
# Problem

Currently the supported environments for developing the project are `poetry` and `docker+poetry`. As you probably well know, neither of these are work very well on Windows. An alternative is `conda` which overhauls the whole installation process for compiled Python dependencies. It works okay(ish) on Windows and especially many data scientists are used to the tooling. Supporting might make development easier for some people.

# Solution

A simple `environment.yml` allows the creation of a working development environment:

~~~yml
name: eis_toolkit

channels:
  - conda-forge

# Changes here should be kept in sync with ./pyproject.toml
dependencies:
  - python >=3.10
  - gdal >=3.4.3
  - rasterio >=1.3.0,<1.4.0
  - pandas >=1.4.3,<1.5
  - geopandas >=0.11.1,<0.12
  - scikit-learn >=1.1.2,<1.2.0
  - matplotlib-base
  - statsmodels >=0.13.2,<0.14.0
  - keras >=2.9.0
  - tensorflow >=2.9.1
  - mkdocs-material >=8.4.0,<8.5.0
  # Dependencies for testing
  - pytest
~~~

The current test suite is also passed by this environment definition.

# Implementation

Just requires adding the shown `environment.yml` file to the project.

Some of the version are not locked and differ from `pyproject.toml` due some combinations of versions being unable to be installed with `conda` based on some brief testing. I can iterate on the versions if it is deemed necessary at this point.

Additionally, to keep the `environment.yml` consistent with the `poetry` environment it is quite easy to add a `conda` workflow to test the environment with the existing test suite in different operating system. E.g. <https://github.com/nialov/fractopo/blob/master/.github/workflows/conda.yml>. In the future, if it is wanted, the package can also be distributed with `conda` using the `conda-forge` feedstock system.

I can do a pull request for the environment and workflow implementation if you consider it suitable. Understandably this adds some overhead and possibility for errors between programmers but maybe the pros outweigh the cons.

# Also

To introduce myself here: I, Nikolas Ovaskainen (nikolas.ovaskainen@gtk.fi), am a research scientist at the Geological Survey of Finland. I have working time for this project this year, so I will (hopefully) be making some feature contributions soon-ish.

### PR DESCRIPTION
**Pull request by nialov**
As introduced in #87 I have implemented a `conda` dependency environment along with an automated GitHub Action workflow to test the environment with the `pytest` test suite. I will keep this as a draft pull request while I iterate on the environment and the GitHub actions and should not be merged yet.

### CODE REVIEW

**Comment by nialov** [comment]
@nmaarnio Could you enable the workflows? (So I do not have to change the workflow `yaml` files to enable them on any pushes on any branch on my fork.)

**Comment by nialov** [comment]
And I will add a short documentation of this installation method in `README.md` as I go along.

**Comment by nialov** [comment]
Just an update: the current dependency specification is difficult to get working on `conda` on Windows with all the dependencies. I will continue trying in a week or two.

**Review by nmaarnio — APPROVED** [review]
Looks good. Thanks for adding conda support!

**Pull request merged**
